### ISSUE TITLE
关于Parser的问题

### ISSUE THREAD

**Issue by thautwarm** [xia-st/JPython#1]
我看了一下你的Compiler，感觉你在翻译CPython的C码源呀。  
个人有一些小的建议...：
-  按照CPython的Grammar，利用Parser工具构建编译器前端，在兼容CPython语法的基础上，添加一些觉得有用的新语法...
-  拿到Ast后，直接利用Java现有的特性，去模拟Python的特性。抛弃CPython模拟栈帧的那一套。

但是你都翻译那么多了。。

**Comment by thautwarm** [comment]
嘛，我主要是看了一下结构像CPython码源，然后翻到了GramInit.java文件。。。

**Comment by xia-st** [comment]
嗯。。。是的，其实我当时就是在翻译代码来着，边翻译边学嘛。
不过在写ast的时候发现了cpython中用了一个c语言的特性，java中没法实现。。。于是只好用了一堆instance of，其实到现在还是在想怎样实现比较优雅(>﹏<)。
还有就是，这里grammar的parser工具其实是我自己写的呐～看了cpython最终生成的结果感觉挺好玩的，于是就自己用python也写了一个。
嗯，还有一点就是，其实这段代码也是才写到生成ast的说2333，后面都还没写下去，当初为了交毕业设计赶工搞了个超级随便的后端。。。代码简陋到都不想提交上来

**Comment by xia-st** [comment]
哈哈，这个GramInit就是工具生成的～主要看官方的实现很完美，占用空间极少，而且是O(1)的算法，就照着来了

**Comment by thautwarm** [comment]
嗷，了解啦。parser工具是自己写的呀，感觉这个项目其实含金量很高啊。。
毕业设计结果应该不错的吧？(虽然我很怀疑一般老师能否接受这种程度的毕业设计。。其实很可能因为自己不理解所以只给个良的吧。。。
所以你都毕业了啊，现在混得如何2333

**Comment by thautwarm** [comment]
是的，官方实现我只能说刷新了我对C宏的认知。。以前我们老师说C宏不是好东西，不建议用。。想来真是差点误终生

**Comment by xia-st** [comment]
嗯。。。妳猜对了，的确就只有一个良。。。😂我现在在一个小城市工作来着23333不算差就是了。

C宏那么好的东西怎么可能不用嘛！不过老师这么说估计是为了让大家减少犯错吧，比如怕在define的时候忘记加括号什么的。。。

**Comment by thautwarm** [comment]
@xia-st 诶，我觉得好可惜啊。。  
那你现在满意自己的发展嘛。。我觉得以你之前写的项目涉及的东西。。。感觉是那种要搞大新闻的节奏啊。。  
但看起来你好像开始沉迷摸鱼了？？？  
突然想到自己的未来。。(诶，摸鱼特挺好哈哈哈
那现在业余时间多嘛？有没有时间写自己喜欢的东西呢？

**Comment by xia-st** [comment]
@thautwarm 嗯，工作什么的目前这个还毕竟轻松啦，不过要继续开巨坑的话估计会没有休息时间？

现在主要再写一些小玩具什么的，偶尔玩玩树莓派。
